-- By Zisu (http://www.curse-gaming.com/en/profile-122056.html)
local AceLocale = AceLibrary("AceLocale-2.2"):new("HealOrganizer")

AceLocale:RegisterTranslations("enUS", function()
    return {
        ["CLOSE"] = "Close",
        ["RESET"] = "Reset",
        ["RAID"] = "Raid",
        ["CHANNEL"] = "Channel",
        ["DISPEL"] = "Dispel",
        ["MT"] = "MT",
        ["HEAL"] = "Heal",
        ["DECURSE"] = "Decurse",
        ["REMAINS"] = "Remaining",
        ["ARRANGEMENT"] = "Arrangement",
        ["BROADCAST"] = "Broadcast",
        ["OPTIONS"] = "Options",
        ["STATS"] = "Statistics",
        ["PALADIN"] = "Paladin",
        ["DRUID"] = "Druid",
        ["PRIEST"] = "Priest",
        ["SHAMAN"] = "Shaman",
        ["PALADINS"] = "Paladins",
        ["DRUIDS"] = "Druids",
        ["PRIESTS"] = "Priests",
        ["SHAMANS"] = "Shamans",
        ["HEALARRANGEMENT"] = "Healing arrangement",
        ["FFA"] = "ffa", -- was der rest machen darf
        ["NO_CHANNEL"] = "You must join channel %q before broadcasting the healing arrangement to it",
        ["NOT_IN_RAID"] = "You are not in a raid",
        ["FREE"] = "Empty",
        ["EDIT_LABEL"] = "New label for group %u",
        ["SHOW_DIALOG"] = "Show/Hide the dialog",
        ["LABELS"] = "Labels",
        ["SAVEAS"] = "Save as",
        ["SET_SAVEAS"] = "Enter a name for the new set",
        ["SET_DEFAULT"] = "Default",
        ["SET_CANNOT_DELETE_DEFAULT"] = "You cannot delete the default set",
        ["SET_CANNOT_SAVE_DEFAULT"] = "You cannot overwrite the default set",
        ["SET_ALREADY_EXISTS"] = "The set %q already exists",
        ["SET_TO_MANY_SETS"] = "You cannot have more than 32 sets",
        ["AUTOSORT_DESC"] = "Autosort for groups",
        ["REPLY_NO_ARRANGEMENT"] = "You weren't assigned.",
        ["REPLY_ARRANGEMENT_FOR"] = "You are assigned to %s.",
        ["AUTOFILL"] = "Autofill",
        ["MSG_HEAL_FOR_ARRANGEMENT"] = "Whisper 'heal' for your assignment.",
        ["WHISPER"] = "Whisper healers their assignment.",
        ["ARRANGEMENT_FOR"] = "Your arrangement: %s",
        ["BROADCAST_RAID"] = "Broadcast assignments to the raid.",
		["BROADCAST_CHAN"] = "Broadcast assignments to the channel.",
    }
end)
