--[[
************************************************************************
esMX.lua
esMX localization strings for Heal Organizer
************************************************************************
File date: @file-date-iso@ 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: @project-version@
************************************************************************
Translation credits: http://www.wowace.com/addons/heal-organizer/localization/translators/

Please update http://www.wowace.com/addons/heal-organizer/localization/esMX/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.
************************************************************************
Please see http://www.wowace.com/addons/heal-organizer/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("HealOrganizer", "esMX", false)

if not L then return end

--@localization(locale="esMX", format="lua_additive_table", handle-unlocalized="ignore", escape-non-ascii=false, same-key-is-true=true)@